config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users

  resources :profiles, only: [:index, :edit, :update, :show, :destroy] do
    resources :friendships
  end

  resources :posts

  root to: "home#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :post, :content, :user, presence: true
  validates_uniqueness_of :comment_id, scope: :user_id
end

app/models/diet.rb
class Diet < ActiveRecord::Base
  has_many :user_diets
  has_many :users, through: :user_diets
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  has_many :user_interests
  has_many :users, through: :user_interests
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  has_many :user_medications
  has_many :users, through: :user_medications

  default_scope { order('description ASC') }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy

  accepts_nested_attributes_for :comments

  validates_presence_of :user, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  validates :content, presence: true
  validates_associated :comments

  PRIVACY = [["Public", "La communauté" ], ["Mes amis", "Amis"]]
end

app/models/supplement.rb
class Supplement < ActiveRecord::Base
  has_many :user_supplements
  has_many :users, through: :user_supplements
end

app/models/symptom.rb
class Symptom < ActiveRecord::Base
  has_many :user_symptoms
  has_many :users, through: :user_symptoms
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => 'Friendship', :foreign_key => 'friend_id'
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, :dependent => :destroy
  accepts_nested_attributes_for :posts,:reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  has_many :comments, through: :posts

  has_many :user_interests
  has_many :interests, through: :user_interests
  has_many :events
  has_many :experiences
  has_many :user_symptoms
  has_many :symptoms, through: :user_symptoms
  has_many :user_medications
  has_many :medications, through: :user_medications
  has_many :user_supplements
  has_many :supplements, through: :user_supplements
  has_many :user_wellbeings
  has_many :wellbeings, through: :user_wellbeings

  #validates :first_name, :email, :password, presence: true

end

app/models/user_diet.rb
class UserDiet < ActiveRecord::Base
  belongs_to :user
  belongs_to :diet
end

app/models/user_interest.rb
class UserInterest < ActiveRecord::Base
  belongs_to :user
  belongs_to :interest
end

app/models/user_medication.rb
class UserMedication < ActiveRecord::Base
  belongs_to :user
  belongs_to :medication

  validates_presence_of :medication, :user
  validates_uniqueness_of :medication_id, scope: :user_id
end

app/models/user_supplement.rb
class UserSupplement < ActiveRecord::Base
  belongs_to :user
  belongs_to :supplement
end

app/models/user_symptom.rb
class UserSymptom < ActiveRecord::Base
  belongs_to :user
  belongs_to :symptom
end

app/models/user_wellbeing.rb
class UserWellbeing < ActiveRecord::Base
  belongs_to :user
  belongs_to :wellbeing
end

app/models/wellbeing.rb
class Wellbeing < ActiveRecord::Base
  has_many :user_wellbeings
  has_many :users, through: :user_wellbeings
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
    @user = User.where(id: params[:user_id]).first || current_user
    @posts = Post.all
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to profile_path(current_user), notice: 'Merci, votre profil a bien été créé.'
    else
      render :edit, notice: 'Mince, réessayer svp.'
    end
  end

  def destroy
    current_user.destroy
    redirect_to root_path,  notice: 'Votre profil a bien été supprimé'
  end

private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:first_name, :birth_date, :picture, :address, :city, :country, :zipcode, :mood, medication_ids: [ ])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<h1 class="container text-center">Complétez votre profil</h1>
  <br>
  <br>
  <br>
  <div class= "title text-center"><strong>VOS COORDONNEES</strong>
    <br>
    <br>
      <div class="container text-align">
        <div class="row">
          <div class="col-xs-4 col-xs-offset-4">
          <%= bootstrap_form_for(current_user, url: profile_path(current_user)) do |f| %>
              <%= f.text_field :first_name, label: "Prénom", placeholder: "Prénom" %>
              <%= f.text_field :birth_date, label: "Date de naissance", placeholder: "Date de naissance" %>
              <%= f.text_field :address, label: "Adresse", placeholder: "Adresse" %>
              <%= f.text_field :zipcode, label: "Code postal", placeholder: "Code Postal" %>
              <%= f.text_field :city, label: "Ville", placeholder: "Ville" %>
              <%= f.text_field :country, label: "Pays", placeholder: "Pays" %>
          </div>
        </div>
      </div>
  <br>
  <br>
        <div class="medications"><strong>VOTRE TRAITEMENT</strong></div>

              <div class="container">
                  <div class= "row">
                    <br>
                     <br>
                      <% Medication.all.each do |medication| %>
                        <div class="col-xs-12 col-sm-4">
                          <div class="checkbox-inline">
                            <label>
                              <%= check_box_tag "user[medication_ids][]", medication.id, current_user.medication_ids.include?(medication.id) %>
                              <%= medication.description %>
                            </label>
                          </div>
                        </div>
                    <% end %>
                  </div>
              </div>
              <br>
            <br>
        <%= f.submit "Créer votre profile", class: "btn btn-primary" %>
      <% end %>
  </div>
<br>
<br>

app/views/profiles/destroy.html.erb
<h1>Profiles#destroy</h1>
<p>Find me in app/views/profiles/destroy.html.erb</p>

app/views/profiles/edit.html.erb
<%= render 'profiles/form' %>

app/views/profiles/index.html.erb
<h1>Vos amis</h1>
<div id="@users">
<% for user in @users %>
  <div class="user">
    <p>
      <strong><%= user.firstname%></strong>
      <%= link_to "Add Friend", friendship_path(:friend_id => user), :method => :post %>
      <div class="clear">
      </div>
    </p>
  </div>
<% end %>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <h1> Je crée mon profile </h1>
         <%= render "form" %>
      <br>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<h1 class="text-center">Mon profil</h1>
<br>
<br>
<br>
<div class="container text-align">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
       <p><strong>First name:</strong> <%= @user.first_name.capitalize%></p>
      <div class="spacer"></div>
      <p><strong>Last name:</strong> <%= @user.birth_date %></p>
      <div class="spacer"></div>
      <p><strong>Email:</strong> <%= @user.email %></p>
      <br>
      <br>
      <strong>MES TRAITEMENTS</strong>
      <% @user.medications.each do |medications| %>
      <br>
      <br>
      <%= medications.description %>
      <% end %>
      <br>
      <br>
      <br>
      <%= link_to(edit_profile_path, class: "btn btn-primary") do %>
        <i class="fa fa-pencil">   Ajouter ou mettre à jour mon profil</i>
      <% end %>
      <div class="horizontal_spacer"></div>
      <div class="horizontal_spacer"></div>
      <div class="horizontal_spacer"></div>
    </div>
  </div>
</div>
<br>
<br>
<div class="container text-align">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <h2>Mes amis</h2>
      <ul>
        <% for friendship in @user.friendships %>
          <li><%= friendship.friend.first_name.capitalize %>
            <div class="spacer">
            <%= link_to "Retirer de ma liste d'amis", profile_friendship_path(current_user.friendships, friendship), :method => :delete, data: { confirm: 'Etes-vous sûr ?' } %>
            </div>
          </li>
        <% end %>
      </ul>
  <br>
<br>
<div class="container text-align">
  <div class="row">
    <%= link_to "Voir mon fil d'actualité", posts_path %>
      <br>
      <br>
    <%= link_to "Poster un status", new_post_path %>
  </div>
</div>
<br>
<br>

<div class="container text-align">
  <div class="col-xs-10">
    <p><strong>MES POSTS</strong></p>
      <% @posts.each do |post| %>
        <div class="row">
          <div class="col-xs-8">
            <% if post.user_id == current_user.id %>
              <%= post.content %>
            <% end %>
          </div>
        </div>
      <% end %>
  </div>
</div>
<br>
<br>
<br>
<br>

app/views/profiles/update.html.erb
<h1>Profiles#update</h1>
<p>Find me in app/views/profiles/update.html.erb</p>