config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :users

  resources :profiles, only: [:index, :edit, :update, :show, :destroy] do
    resources :friendships
  end

  resources :posts

  root to: "home#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :post, :content, :user, presence: true
  validates_uniqueness_of :comment_id, scope: :user_id
end

app/models/diet.rb
class Diet < ActiveRecord::Base
  has_many :user_diets
  has_many :users, through: :user_diets
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  has_many :user_interests
  has_many :users, through: :user_interests
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  has_many :user_medications
  has_many :users, through: :user_medications

  default_scope { order('description ASC') }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy

  accepts_nested_attributes_for :comments

  validates_presence_of :user, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  validates :content, presence: true
  validates_associated :comments

  PRIVACY = [["Public", "La communauté" ], ["Mes amis", "Amis"]]
end

app/models/supplement.rb
class Supplement < ActiveRecord::Base
  has_many :user_supplements
  has_many :users, through: :user_supplements
end

app/models/symptom.rb
class Symptom < ActiveRecord::Base
  has_many :user_symptoms
  has_many :users, through: :user_symptoms
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => 'Friendship', :foreign_key => 'friend_id'
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, :dependent => :destroy
  accepts_nested_attributes_for :posts,:reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  has_many :comments, through: :posts

  has_many :user_interests
  has_many :interests, through: :user_interests
  has_many :events
  has_many :experiences
  has_many :user_symptoms
  has_many :symptoms, through: :user_symptoms
  has_many :user_medications
  has_many :medications, through: :user_medications
  has_many :user_supplements
  has_many :supplements, through: :user_supplements
  has_many :user_wellbeings
  has_many :wellbeings, through: :user_wellbeings

  #validates :first_name, :email, :password, presence: true

end

app/models/user_diet.rb
class UserDiet < ActiveRecord::Base
  belongs_to :user
  belongs_to :diet
end

app/models/user_interest.rb
class UserInterest < ActiveRecord::Base
  belongs_to :user
  belongs_to :interest
end

app/models/user_medication.rb
class UserMedication < ActiveRecord::Base
  belongs_to :user
  belongs_to :medication

  validates_presence_of :medication, :user
  validates_uniqueness_of :medication_id, scope: :user_id
end

app/models/user_supplement.rb
class UserSupplement < ActiveRecord::Base
  belongs_to :user
  belongs_to :supplement
end

app/models/user_symptom.rb
class UserSymptom < ActiveRecord::Base
  belongs_to :user
  belongs_to :symptom
end

app/models/user_wellbeing.rb
class UserWellbeing < ActiveRecord::Base
  belongs_to :user
  belongs_to :wellbeing
end

app/models/wellbeing.rb
class Wellbeing < ActiveRecord::Base
  has_many :user_wellbeings
  has_many :users, through: :user_wellbeings
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_user, only: [:new, :create]
  before_action :set_post, only: [:show]

  def new
    @post = current_user.posts.new
  end

  def create
    @post= current_user.posts.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to profile_path(current_user), notice: 'Bravo, votre post a bien été publié.'
    else
      render :new, notice: 'Petit problème... réessayer svp.'
    end
  end

  def index
    @user = User.where(id: params[:user_id]).first || current_user
    @posts = Post.all
  end

  end

  def show
  end

  def edit
    redirect_to posts_path unless @post.user = current_user
  end

  def update
    if @post.user == current_user
        if @post.update(post_params)
          redirect_to profile_path(current_user), notice: 'Bravo, votre post a bien été modifié.'
        else
          render 'edit'
        end
    else
        redirect_to posts_path
        flash[:notice] = "Vous ne pouvez pas modifié ce message"
    end
  end


  def destroy
   if @post.destroy
      redirect_to profile_path(current_user), notice: "Votre status a bien été supprimé."
   else
     redirect_to posts_path
     flash[:notice] = "Vous ne pouvez pas modifier ce message"
   end
  end

  private

  def set_user
    @user = current_user
  end

  def set_post
     @post = current_user.posts.find(params[:post_id])
  end

  # def comment_params
  #   params.require(:comment).permit(:content)
  # end

  def post_params
    params.require(:post).permit(:content, :privacy, :user_id, comments_attributes: [:content])
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/posts/_form.html.erb
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-xs-offset-3 col-xs-6">
      <div class="border">

        <%= bootstrap_form_for(@post) do |f| %>
          <div class="form-group">

            <%= f.text_area :content, class: "form-control", label: "Postez votre message" %>
            <% f.fields_for :posts do |f| %>
            <%= f.label :content, "Message" %>
            <%= text_area_tag(:content, nil, class: "form-control") %>
            <% end %>
          </div>

          <div class='form-group'>
            <div class="privacy">
              <%#= select_tag :privacy, options_for_select(Post::PRIVACY), label: "Personnaliser" %>
              <%= f.select :privacy, options_for_select([["Public", 0], ["Mes amis", 1]], :selected => f.object.privacy), label: "Confidentialité" %>
            </div>
          </div>
          <div class="actions text-center" id="submit-button">
              <%= f.submit "Publier", class: 'btn btn-danger' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<div class="container text-align">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <p><strong>MON FIL D'ACTUALITE</p></strong>
        <% @posts.each do |post| %>
          <% if post.privacy == "0" %>
            <%= post.content %>
          <% end %>
          <br>
          <% if post.user_id == current_user.friend_ids %>
            <%= post.content %>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>